// <auto-generated />
using System.Numerics;
using System.Text.Json;
using Database.Main;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Main.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260318041030_Update35_AddTransactionDebugComment")]
    partial class Update35_AddTransactionDebugComment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.Main.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ADDRESS")
                        .HasColumnType("text");

                    b.Property<string>("ADDRESS_NAME")
                        .HasColumnType("text");

                    b.Property<string>("AVATAR")
                        .HasColumnType("text");

                    b.Property<int?>("AddressValidatorKindId")
                        .HasColumnType("integer");

                    b.Property<long>("BALANCE_DIRTY_BLOCK")
                        .HasColumnType("bigint");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<long?>("FIRST_TX_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<long>("NAME_LAST_UPDATED_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("STAKED_AMOUNT")
                        .HasColumnType("text");

                    b.Property<string>("STAKED_AMOUNT_RAW")
                        .HasColumnType("text");

                    b.Property<long>("STAKE_TIMESTAMP")
                        .HasColumnType("bigint");

                    b.Property<long>("STORAGE_AVAILABLE")
                        .HasColumnType("bigint");

                    b.Property<long>("STORAGE_USED")
                        .HasColumnType("bigint");

                    b.Property<BigInteger>("TOTAL_SOUL_AMOUNT")
                        .HasColumnType("numeric");

                    b.Property<string>("UNCLAIMED_AMOUNT")
                        .HasColumnType("text");

                    b.Property<string>("UNCLAIMED_AMOUNT_RAW")
                        .HasColumnType("text");

                    b.Property<string>("USER_NAME")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("AddressValidatorKindId");

                    b.HasIndex("ADDRESS", "ADDRESS_NAME");

                    b.HasIndex("ChainId", "ADDRESS")
                        .IsUnique();

                    b.HasIndex("ChainId", "BALANCE_DIRTY_BLOCK");

                    b.HasIndex("ChainId", "FIRST_TX_UNIX_SECONDS");

                    b.HasIndex("ChainId", "NAME_LAST_UPDATED_UNIX_SECONDS");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Database.Main.AddressBalance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AMOUNT")
                        .HasColumnType("text");

                    b.Property<BigInteger>("AMOUNT_RAW")
                        .HasColumnType("numeric");

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("TokenId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("TokenId");

                    b.HasIndex("AddressId", "TokenId")
                        .IsUnique();

                    b.ToTable("AddressBalances");
                });

            modelBuilder.Entity("Database.Main.AddressTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("TransactionId");

                    b.HasIndex("AddressId", "TransactionId")
                        .IsUnique();

                    b.ToTable("AddressTransactions");
                });

            modelBuilder.Entity("Database.Main.AddressValidatorKind", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("NAME");

                    b.ToTable("AddressValidatorKinds");
                });

            modelBuilder.Entity("Database.Main.Block", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ChainAddressId")
                        .HasColumnType("integer");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<string>("HASH")
                        .HasColumnType("text");

                    b.Property<long>("HEIGHT")
                        .HasColumnType("bigint");

                    b.Property<string>("PREVIOUS_HASH")
                        .HasColumnType("text");

                    b.Property<int>("PROTOCOL")
                        .HasColumnType("integer");

                    b.Property<string>("REWARD")
                        .HasColumnType("text");

                    b.Property<long>("TIMESTAMP_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<int>("ValidatorAddressId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ChainAddressId");

                    b.HasIndex("HASH")
                        .IsUnique()
                        .HasDatabaseName("IX_Search_Blocks_Hash_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HASH"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("HASH"), new[] { "gin_trgm_ops" });

                    b.HasIndex("HEIGHT")
                        .HasDatabaseName("IX_Search_Blocks_Height");

                    b.HasIndex("TIMESTAMP_UNIX_SECONDS");

                    b.HasIndex("ValidatorAddressId");

                    b.HasIndex("ChainId", "HEIGHT");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Database.Main.BlockOracle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("BlockId")
                        .HasColumnType("integer");

                    b.Property<int>("OracleId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("BlockId");

                    b.HasIndex("OracleId");

                    b.ToTable("BlockOracles");
                });

            modelBuilder.Entity("Database.Main.Chain", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<long>("CURRENT_HEIGHT")
                        .HasColumnType("bigint");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("NAME")
                        .IsUnique();

                    b.ToTable("Chains");
                });

            modelBuilder.Entity("Database.Main.Contract", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<int?>("ContractMethodId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreateEventId")
                        .HasColumnType("integer");

                    b.Property<string>("HASH")
                        .HasColumnType("text");

                    b.Property<long>("LAST_UPDATED_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.Property<string>("SCRIPT_RAW")
                        .HasColumnType("text");

                    b.Property<string>("SYMBOL")
                        .HasColumnType("text");

                    b.Property<int?>("TokenId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContractMethodId");

                    b.HasIndex("CreateEventId")
                        .IsUnique();

                    b.HasIndex("TokenId")
                        .IsUnique();

                    b.HasIndex("ChainId", "HASH")
                        .IsUnique();

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Database.Main.ContractMethod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<JsonElement>("METHODS")
                        .HasColumnType("jsonb");

                    b.Property<long>("TIMESTAMP_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractMethods");
                });

            modelBuilder.Entity("Database.Main.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<bool>("BLACKLISTED")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BURNED")
                        .HasColumnType("boolean");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<long>("DATE_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<long>("DM_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<int>("EventKindId")
                        .HasColumnType("integer");

                    b.Property<int>("INDEX")
                        .HasColumnType("integer");

                    b.Property<bool>("NSFW")
                        .HasColumnType("boolean");

                    b.Property<int?>("NftId")
                        .HasColumnType("integer");

                    b.Property<string>("PAYLOAD_FORMAT")
                        .HasColumnType("text");

                    b.Property<string>("PAYLOAD_JSON")
                        .HasColumnType("jsonb");

                    b.Property<string>("RAW_DATA")
                        .HasColumnType("text");

                    b.Property<long>("TIMESTAMP_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<string>("TOKEN_ID")
                        .HasColumnType("text");

                    b.Property<int?>("TargetAddressId")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AddressId");

                    b.HasIndex("ChainId");

                    b.HasIndex("DATE_UNIX_SECONDS");

                    b.HasIndex("EventKindId");

                    b.HasIndex("NftId");

                    b.HasIndex("TIMESTAMP_UNIX_SECONDS");

                    b.HasIndex("TargetAddressId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("BURNED", "EventKindId");

                    b.HasIndex("ContractId", "TOKEN_ID");

                    b.HasIndex("EventKindId", "ID");

                    b.HasIndex("EventKindId", "ChainId", "TIMESTAMP_UNIX_SECONDS", "ID")
                        .HasDatabaseName("IX_Events_EventKind_Chain_Timestamp_Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Database.Main.EventKind", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ChainId", "NAME")
                        .IsUnique();

                    b.ToTable("EventKinds");
                });

            modelBuilder.Entity("Database.Main.External", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("HASH")
                        .HasColumnType("text");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.Property<int>("TokenId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("PlatformId");

                    b.HasIndex("TokenId");

                    b.ToTable("Externals");
                });

            modelBuilder.Entity("Database.Main.FiatExchangeRate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("SYMBOL")
                        .HasColumnType("text");

                    b.Property<decimal>("USD_PRICE")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("SYMBOL")
                        .IsUnique();

                    b.HasIndex("SYMBOL", "USD_PRICE");

                    b.ToTable("FiatExchangeRates");
                });

            modelBuilder.Entity("Database.Main.GlobalVariable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<long>("LONG_VALUE")
                        .HasColumnType("bigint");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.Property<string>("STRING_VALUE")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("NAME")
                        .IsUnique();

                    b.ToTable("GlobalVariables");
                });

            modelBuilder.Entity("Database.Main.Infusion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("KEY")
                        .HasColumnType("text");

                    b.Property<int>("NftId")
                        .HasColumnType("integer");

                    b.Property<int?>("TokenId")
                        .HasColumnType("integer");

                    b.Property<string>("VALUE")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("KEY");

                    b.HasIndex("NftId");

                    b.HasIndex("TokenId");

                    b.ToTable("Infusions");
                });

            modelBuilder.Entity("Database.Main.Nft", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("BLACKLISTED")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BURNED")
                        .HasColumnType("boolean");

                    b.Property<JsonDocument>("CHAIN_API_RESPONSE")
                        .HasColumnType("jsonb");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatorAddressId")
                        .HasColumnType("integer");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("text");

                    b.Property<long>("DM_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<string>("IMAGE")
                        .HasColumnType("text");

                    b.Property<string>("INFO_URL")
                        .HasColumnType("text");

                    b.Property<int?>("InfusedIntoId")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("METADATA")
                        .HasColumnType("jsonb");

                    b.Property<bool?>("METADATA_UPDATE")
                        .HasColumnType("boolean");

                    b.Property<long>("MINT_DATE_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<int>("MINT_NUMBER")
                        .HasColumnType("integer");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.Property<bool>("NSFW")
                        .HasColumnType("boolean");

                    b.Property<JsonDocument>("OFFCHAIN_API_RESPONSE")
                        .HasColumnType("jsonb");

                    b.Property<string>("RAM")
                        .HasColumnType("text");

                    b.Property<string>("ROM")
                        .HasColumnType("text");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<string>("TOKEN_ID")
                        .HasColumnType("text");

                    b.Property<string>("TOKEN_URI")
                        .HasColumnType("text");

                    b.Property<string>("VIDEO")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("BURNED");

                    b.HasIndex("ChainId");

                    b.HasIndex("CreatorAddressId");

                    b.HasIndex("DM_UNIX_SECONDS");

                    b.HasIndex("InfusedIntoId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("TOKEN_ID");

                    b.HasIndex("ContractId", "TOKEN_ID")
                        .IsUnique();

                    b.HasIndex("ContractId", "TOKEN_URI");

                    b.ToTable("Nfts");
                });

            modelBuilder.Entity("Database.Main.NftOwnership", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AMOUNT")
                        .HasColumnType("integer");

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<long>("LAST_CHANGE_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<int>("NftId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("LAST_CHANGE_UNIX_SECONDS");

                    b.HasIndex("NftId");

                    b.HasIndex("AddressId", "NftId")
                        .IsUnique();

                    b.ToTable("NftOwnerships");
                });

            modelBuilder.Entity("Database.Main.Oracle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CONTENT")
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("URL", "CONTENT")
                        .IsUnique();

                    b.ToTable("Oracles");
                });

            modelBuilder.Entity("Database.Main.Organization", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ADDRESS")
                        .HasColumnType("text");

                    b.Property<string>("ADDRESS_NAME")
                        .HasColumnType("text");

                    b.Property<int?>("CreateEventId")
                        .HasColumnType("integer");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.Property<string>("ORGANIZATION_ID")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CreateEventId")
                        .IsUnique();

                    b.HasIndex("NAME")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Database.Main.OrganizationAddress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AddressId");

                    b.HasIndex("OrganizationId", "AddressId")
                        .IsUnique();

                    b.ToTable("OrganizationAddresses");
                });

            modelBuilder.Entity("Database.Main.Platform", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CHAIN")
                        .HasColumnType("text");

                    b.Property<int?>("CreateEventId")
                        .HasColumnType("integer");

                    b.Property<string>("FUEL")
                        .HasColumnType("text");

                    b.Property<bool>("HIDDEN")
                        .HasColumnType("boolean");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CreateEventId")
                        .IsUnique();

                    b.HasIndex("NAME")
                        .IsUnique();

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("Database.Main.PlatformInterop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("EXTERNAL")
                        .HasColumnType("text");

                    b.Property<int>("LocalAddressId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("LocalAddressId");

                    b.HasIndex("PlatformId");

                    b.ToTable("PlatformInterops");
                });

            modelBuilder.Entity("Database.Main.PlatformToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.Property<int>("PlatformId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("NAME");

                    b.HasIndex("PlatformId");

                    b.ToTable("PlatformTokens");
                });

            modelBuilder.Entity("Database.Main.Series", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ATTR_TYPE_1")
                        .HasColumnType("text");

                    b.Property<string>("ATTR_TYPE_2")
                        .HasColumnType("text");

                    b.Property<string>("ATTR_TYPE_3")
                        .HasColumnType("text");

                    b.Property<string>("ATTR_VALUE_1")
                        .HasColumnType("text");

                    b.Property<string>("ATTR_VALUE_2")
                        .HasColumnType("text");

                    b.Property<string>("ATTR_VALUE_3")
                        .HasColumnType("text");

                    b.Property<bool?>("BLACKLISTED")
                        .HasColumnType("boolean");

                    b.Property<int>("CURRENT_SUPPLY")
                        .HasColumnType("integer");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatorAddressId")
                        .HasColumnType("integer");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("text");

                    b.Property<long>("DM_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<bool>("HAS_LOCKED")
                        .HasColumnType("boolean");

                    b.Property<string>("IMAGE")
                        .HasColumnType("text");

                    b.Property<int>("MAX_SUPPLY")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("METADATA")
                        .HasColumnType("jsonb");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.Property<bool?>("NSFW")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ROYALTIES")
                        .HasColumnType("numeric");

                    b.Property<long>("SERIES_CREATED_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<string>("SERIES_ID")
                        .HasColumnType("text");

                    b.Property<int?>("SeriesModeId")
                        .HasColumnType("integer");

                    b.Property<int>("TYPE")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CreatorAddressId");

                    b.HasIndex("SERIES_ID");

                    b.HasIndex("SeriesModeId");

                    b.HasIndex("ContractId", "SERIES_ID")
                        .IsUnique();

                    b.HasIndex("SERIES_CREATED_UNIX_SECONDS", "ID");

                    b.ToTable("Serieses");
                });

            modelBuilder.Entity("Database.Main.SeriesMode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("MODE_NAME")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("MODE_NAME")
                        .IsUnique();

                    b.ToTable("SeriesModes");
                });

            modelBuilder.Entity("Database.Main.Signature", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("DATA")
                        .HasColumnType("text");

                    b.Property<int>("SignatureKindId")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("SignatureKindId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("Database.Main.SignatureKind", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("NAME");

                    b.ToTable("SignatureKinds");
                });

            modelBuilder.Entity("Database.Main.SoulMastersMonthly", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<long>("CAPTURED_AT_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<int>("MASTERS_COUNT")
                        .HasColumnType("integer");

                    b.Property<long>("MONTH_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<string>("SOURCE")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ChainId", "MONTH_UNIX_SECONDS")
                        .IsUnique();

                    b.ToTable("SoulMastersMonthlies");
                });

            modelBuilder.Entity("Database.Main.StakingProgressDaily", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<long>("CAPTURED_AT_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<long>("DATE_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<int>("MASTERS_COUNT")
                        .HasColumnType("integer");

                    b.Property<string>("SOUL_SUPPLY_RAW")
                        .HasColumnType("text");

                    b.Property<string>("SOURCE")
                        .HasColumnType("text");

                    b.Property<string>("STAKED_SOUL_RAW")
                        .HasColumnType("text");

                    b.Property<int>("STAKERS_COUNT")
                        .HasColumnType("integer");

                    b.Property<decimal>("STAKING_RATIO")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("ChainId", "DATE_UNIX_SECONDS")
                        .IsUnique();

                    b.ToTable("StakingProgressDailies");
                });

            modelBuilder.Entity("Database.Main.Token", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<bool>("BURNABLE")
                        .HasColumnType("boolean");

                    b.Property<string>("BURNED_SUPPLY")
                        .HasColumnType("text");

                    b.Property<string>("BURNED_SUPPLY_RAW")
                        .HasColumnType("text");

                    b.Property<byte[]>("CARBON_TOKEN_SCHEMAS")
                        .HasColumnType("bytea");

                    b.Property<string>("CURRENT_SUPPLY")
                        .HasColumnType("text");

                    b.Property<string>("CURRENT_SUPPLY_RAW")
                        .HasColumnType("text");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreateEventId")
                        .HasColumnType("integer");

                    b.Property<int>("DECIMALS")
                        .HasColumnType("integer");

                    b.Property<bool>("DIVISIBLE")
                        .HasColumnType("boolean");

                    b.Property<bool>("FIAT")
                        .HasColumnType("boolean");

                    b.Property<bool>("FINITE")
                        .HasColumnType("boolean");

                    b.Property<bool>("FUEL")
                        .HasColumnType("boolean");

                    b.Property<bool>("FUNGIBLE")
                        .HasColumnType("boolean");

                    b.Property<string>("MAX_SUPPLY")
                        .HasColumnType("text");

                    b.Property<string>("MAX_SUPPLY_RAW")
                        .HasColumnType("text");

                    b.Property<bool>("MINTABLE")
                        .HasColumnType("boolean");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PRICE_AUD")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PRICE_CAD")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PRICE_CNY")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PRICE_EUR")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PRICE_GBP")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PRICE_JPY")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PRICE_RUB")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PRICE_USD")
                        .HasColumnType("numeric");

                    b.Property<string>("SCRIPT_RAW")
                        .HasColumnType("text");

                    b.Property<bool>("STAKABLE")
                        .HasColumnType("boolean");

                    b.Property<bool>("SWAPPABLE")
                        .HasColumnType("boolean");

                    b.Property<string>("SYMBOL")
                        .HasColumnType("text");

                    b.Property<bool>("TRANSFERABLE")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreateEventId")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("SYMBOL", "ChainId");

                    b.HasIndex("ChainId", "ContractId", "SYMBOL")
                        .IsUnique();

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Database.Main.TokenDailyPrice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<long>("DATE_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PRICE_USD")
                        .HasColumnType("numeric");

                    b.Property<int>("TokenId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("DATE_UNIX_SECONDS");

                    b.HasIndex("TokenId");

                    b.ToTable("TokenDailyPrices");
                });

            modelBuilder.Entity("Database.Main.TokenLogo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("TokenId")
                        .HasColumnType("integer");

                    b.Property<int>("TokenLogoTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("TokenLogoTypeId");

                    b.HasIndex("TokenId", "TokenLogoTypeId")
                        .IsUnique();

                    b.ToTable("TokenLogos");
                });

            modelBuilder.Entity("Database.Main.TokenLogoType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("NAME");

                    b.ToTable("TokenLogoTypes");
                });

            modelBuilder.Entity("Database.Main.Transaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("BlockId")
                        .HasColumnType("integer");

                    b.Property<string>("CARBON_TX_DATA")
                        .HasColumnType("text");

                    b.Property<byte?>("CARBON_TX_TYPE")
                        .HasColumnType("smallint");

                    b.Property<string>("DEBUG_COMMENT")
                        .HasColumnType("text");

                    b.Property<long>("EXPIRATION")
                        .HasColumnType("bigint");

                    b.Property<string>("FEE")
                        .HasColumnType("text");

                    b.Property<string>("FEE_RAW")
                        .HasColumnType("text");

                    b.Property<string>("GAS_LIMIT")
                        .HasColumnType("text");

                    b.Property<string>("GAS_LIMIT_RAW")
                        .HasColumnType("text");

                    b.Property<string>("GAS_PRICE")
                        .HasColumnType("text");

                    b.Property<string>("GAS_PRICE_RAW")
                        .HasColumnType("text");

                    b.Property<int>("GasPayerId")
                        .HasColumnType("integer");

                    b.Property<int>("GasTargetId")
                        .HasColumnType("integer");

                    b.Property<string>("HASH")
                        .HasColumnType("text");

                    b.Property<int>("INDEX")
                        .HasColumnType("integer");

                    b.Property<string>("PAYLOAD")
                        .HasColumnType("text");

                    b.Property<string>("RESULT")
                        .HasColumnType("text");

                    b.Property<string>("SCRIPT_RAW")
                        .HasColumnType("text");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<long>("TIMESTAMP_UNIX_SECONDS")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("GasPayerId");

                    b.HasIndex("GasTargetId");

                    b.HasIndex("HASH")
                        .HasDatabaseName("IX_Search_Transactions_Hash_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HASH"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("HASH"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SenderId");

                    b.HasIndex("StateId");

                    b.HasIndex("TIMESTAMP_UNIX_SECONDS");

                    b.HasIndex("BlockId", "INDEX");

                    b.HasIndex("TIMESTAMP_UNIX_SECONDS", "ID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Database.Main.TransactionState", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("NAME");

                    b.ToTable("TransactionStates");
                });

            modelBuilder.Entity("Database.Main.Address", b =>
                {
                    b.HasOne("Database.Main.AddressValidatorKind", "AddressValidatorKind")
                        .WithMany("Addresses")
                        .HasForeignKey("AddressValidatorKindId");

                    b.HasOne("Database.Main.Chain", "Chain")
                        .WithMany("Addresses")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressValidatorKind");

                    b.Navigation("Chain");
                });

            modelBuilder.Entity("Database.Main.AddressBalance", b =>
                {
                    b.HasOne("Database.Main.Address", "Address")
                        .WithMany("AddressBalances")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Token", "Token")
                        .WithMany("AddressBalances")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Database.Main.AddressTransaction", b =>
                {
                    b.HasOne("Database.Main.Address", "Address")
                        .WithMany("AddressTransactions")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Transaction", "Transaction")
                        .WithMany("TransactionAddresses")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Database.Main.Block", b =>
                {
                    b.HasOne("Database.Main.Address", "ChainAddress")
                        .WithMany("ChainAddressBlocks")
                        .HasForeignKey("ChainAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Chain", "Chain")
                        .WithMany("Blocks")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Address", "ValidatorAddress")
                        .WithMany("ValidatorAddressBlocks")
                        .HasForeignKey("ValidatorAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chain");

                    b.Navigation("ChainAddress");

                    b.Navigation("ValidatorAddress");
                });

            modelBuilder.Entity("Database.Main.BlockOracle", b =>
                {
                    b.HasOne("Database.Main.Block", "Block")
                        .WithMany("BlockOracles")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Oracle", "Oracle")
                        .WithMany("BlockOracles")
                        .HasForeignKey("OracleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("Oracle");
                });

            modelBuilder.Entity("Database.Main.Contract", b =>
                {
                    b.HasOne("Database.Main.Address", "Address")
                        .WithMany("Contracts")
                        .HasForeignKey("AddressId");

                    b.HasOne("Database.Main.Chain", "Chain")
                        .WithMany("Contracts")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.ContractMethod", "ContractMethod")
                        .WithMany("Contracts")
                        .HasForeignKey("ContractMethodId");

                    b.HasOne("Database.Main.Event", "CreateEvent")
                        .WithOne("CreateContract")
                        .HasForeignKey("Database.Main.Contract", "CreateEventId");

                    b.HasOne("Database.Main.Token", "Token")
                        .WithOne("Contract")
                        .HasForeignKey("Database.Main.Contract", "TokenId");

                    b.Navigation("Address");

                    b.Navigation("Chain");

                    b.Navigation("ContractMethod");

                    b.Navigation("CreateEvent");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Database.Main.ContractMethod", b =>
                {
                    b.HasOne("Database.Main.Contract", "Contract")
                        .WithMany("ContractMethods")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Database.Main.Event", b =>
                {
                    b.HasOne("Database.Main.Address", "Address")
                        .WithMany("Events")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Chain", "Chain")
                        .WithMany("Events")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Contract", "Contract")
                        .WithMany("Events")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.EventKind", "EventKind")
                        .WithMany("Events")
                        .HasForeignKey("EventKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Nft", "Nft")
                        .WithMany("Events")
                        .HasForeignKey("NftId");

                    b.HasOne("Database.Main.Address", "TargetAddress")
                        .WithMany("ValidatorEvents")
                        .HasForeignKey("TargetAddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Main.Transaction", "Transaction")
                        .WithMany("Events")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Chain");

                    b.Navigation("Contract");

                    b.Navigation("EventKind");

                    b.Navigation("Nft");

                    b.Navigation("TargetAddress");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Database.Main.EventKind", b =>
                {
                    b.HasOne("Database.Main.Chain", "Chain")
                        .WithMany("EventKinds")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chain");
                });

            modelBuilder.Entity("Database.Main.External", b =>
                {
                    b.HasOne("Database.Main.Platform", "Platform")
                        .WithMany("Externals")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Token", "Token")
                        .WithMany("Externals")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Database.Main.Infusion", b =>
                {
                    b.HasOne("Database.Main.Nft", "Nft")
                        .WithMany("Infusions")
                        .HasForeignKey("NftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Token", "Token")
                        .WithMany("Infusions")
                        .HasForeignKey("TokenId");

                    b.Navigation("Nft");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Database.Main.Nft", b =>
                {
                    b.HasOne("Database.Main.Chain", "Chain")
                        .WithMany("Nfts")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Contract", "Contract")
                        .WithMany("Nfts")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Address", "CreatorAddress")
                        .WithMany("Nfts")
                        .HasForeignKey("CreatorAddressId");

                    b.HasOne("Database.Main.Nft", "InfusedInto")
                        .WithMany("InfusedNfts")
                        .HasForeignKey("InfusedIntoId");

                    b.HasOne("Database.Main.Series", "Series")
                        .WithMany("Nfts")
                        .HasForeignKey("SeriesId");

                    b.Navigation("Chain");

                    b.Navigation("Contract");

                    b.Navigation("CreatorAddress");

                    b.Navigation("InfusedInto");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Database.Main.NftOwnership", b =>
                {
                    b.HasOne("Database.Main.Address", "Address")
                        .WithMany("NftOwnerships")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Nft", "Nft")
                        .WithMany("NftOwnerships")
                        .HasForeignKey("NftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Nft");
                });

            modelBuilder.Entity("Database.Main.Organization", b =>
                {
                    b.HasOne("Database.Main.Event", "CreateEvent")
                        .WithOne("CreateOrganization")
                        .HasForeignKey("Database.Main.Organization", "CreateEventId");

                    b.Navigation("CreateEvent");
                });

            modelBuilder.Entity("Database.Main.OrganizationAddress", b =>
                {
                    b.HasOne("Database.Main.Address", "Address")
                        .WithMany("OrganizationAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Organization", "Organization")
                        .WithMany("OrganizationAddresses")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Database.Main.Platform", b =>
                {
                    b.HasOne("Database.Main.Event", "CreateEvent")
                        .WithOne("CreatePlatform")
                        .HasForeignKey("Database.Main.Platform", "CreateEventId");

                    b.Navigation("CreateEvent");
                });

            modelBuilder.Entity("Database.Main.PlatformInterop", b =>
                {
                    b.HasOne("Database.Main.Address", "LocalAddress")
                        .WithMany("PlatformInterops")
                        .HasForeignKey("LocalAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Platform", "Platform")
                        .WithMany("PlatformInterops")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalAddress");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Database.Main.PlatformToken", b =>
                {
                    b.HasOne("Database.Main.Platform", "Platform")
                        .WithMany("PlatformTokens")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Database.Main.Series", b =>
                {
                    b.HasOne("Database.Main.Contract", "Contract")
                        .WithMany("Series")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Address", "CreatorAddress")
                        .WithMany("Serieses")
                        .HasForeignKey("CreatorAddressId");

                    b.HasOne("Database.Main.SeriesMode", "SeriesMode")
                        .WithMany("Series")
                        .HasForeignKey("SeriesModeId");

                    b.Navigation("Contract");

                    b.Navigation("CreatorAddress");

                    b.Navigation("SeriesMode");
                });

            modelBuilder.Entity("Database.Main.Signature", b =>
                {
                    b.HasOne("Database.Main.SignatureKind", "SignatureKind")
                        .WithMany("Signatures")
                        .HasForeignKey("SignatureKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Transaction", "Transaction")
                        .WithMany("Signatures")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignatureKind");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Database.Main.SoulMastersMonthly", b =>
                {
                    b.HasOne("Database.Main.Chain", "Chain")
                        .WithMany("SoulMastersMonthlies")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chain");
                });

            modelBuilder.Entity("Database.Main.StakingProgressDaily", b =>
                {
                    b.HasOne("Database.Main.Chain", "Chain")
                        .WithMany("StakingProgressDailies")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chain");
                });

            modelBuilder.Entity("Database.Main.Token", b =>
                {
                    b.HasOne("Database.Main.Address", "Address")
                        .WithMany("Tokens")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Chain", "Chain")
                        .WithMany("Tokens")
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Event", "CreateEvent")
                        .WithOne("CreateToken")
                        .HasForeignKey("Database.Main.Token", "CreateEventId");

                    b.HasOne("Database.Main.Address", "Owner")
                        .WithMany("TokenOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Chain");

                    b.Navigation("CreateEvent");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Database.Main.TokenDailyPrice", b =>
                {
                    b.HasOne("Database.Main.Token", "Token")
                        .WithMany("TokenDailyPrices")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Database.Main.TokenLogo", b =>
                {
                    b.HasOne("Database.Main.Token", "Token")
                        .WithMany("TokenLogos")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.TokenLogoType", "TokenLogoType")
                        .WithMany("TokenLogos")
                        .HasForeignKey("TokenLogoTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");

                    b.Navigation("TokenLogoType");
                });

            modelBuilder.Entity("Database.Main.Transaction", b =>
                {
                    b.HasOne("Database.Main.Block", "Block")
                        .WithMany("Transactions")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Address", "GasPayer")
                        .WithMany("TransactionsWithThisGasPayer")
                        .HasForeignKey("GasPayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Address", "GasTarget")
                        .WithMany("TransactionsWithThisGasTarget")
                        .HasForeignKey("GasTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.Address", "Sender")
                        .WithMany("SentTransactions")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Main.TransactionState", "State")
                        .WithMany("Transactions")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("GasPayer");

                    b.Navigation("GasTarget");

                    b.Navigation("Sender");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Database.Main.Address", b =>
                {
                    b.Navigation("AddressBalances");

                    b.Navigation("AddressTransactions");

                    b.Navigation("ChainAddressBlocks");

                    b.Navigation("Contracts");

                    b.Navigation("Events");

                    b.Navigation("NftOwnerships");

                    b.Navigation("Nfts");

                    b.Navigation("OrganizationAddresses");

                    b.Navigation("PlatformInterops");

                    b.Navigation("SentTransactions");

                    b.Navigation("Serieses");

                    b.Navigation("TokenOwners");

                    b.Navigation("Tokens");

                    b.Navigation("TransactionsWithThisGasPayer");

                    b.Navigation("TransactionsWithThisGasTarget");

                    b.Navigation("ValidatorAddressBlocks");

                    b.Navigation("ValidatorEvents");
                });

            modelBuilder.Entity("Database.Main.AddressValidatorKind", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Database.Main.Block", b =>
                {
                    b.Navigation("BlockOracles");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Database.Main.Chain", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Blocks");

                    b.Navigation("Contracts");

                    b.Navigation("EventKinds");

                    b.Navigation("Events");

                    b.Navigation("Nfts");

                    b.Navigation("SoulMastersMonthlies");

                    b.Navigation("StakingProgressDailies");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Database.Main.Contract", b =>
                {
                    b.Navigation("ContractMethods");

                    b.Navigation("Events");

                    b.Navigation("Nfts");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Database.Main.ContractMethod", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Database.Main.Event", b =>
                {
                    b.Navigation("CreateContract");

                    b.Navigation("CreateOrganization");

                    b.Navigation("CreatePlatform");

                    b.Navigation("CreateToken");
                });

            modelBuilder.Entity("Database.Main.EventKind", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Database.Main.Nft", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("InfusedNfts");

                    b.Navigation("Infusions");

                    b.Navigation("NftOwnerships");
                });

            modelBuilder.Entity("Database.Main.Oracle", b =>
                {
                    b.Navigation("BlockOracles");
                });

            modelBuilder.Entity("Database.Main.Organization", b =>
                {
                    b.Navigation("OrganizationAddresses");
                });

            modelBuilder.Entity("Database.Main.Platform", b =>
                {
                    b.Navigation("Externals");

                    b.Navigation("PlatformInterops");

                    b.Navigation("PlatformTokens");
                });

            modelBuilder.Entity("Database.Main.Series", b =>
                {
                    b.Navigation("Nfts");
                });

            modelBuilder.Entity("Database.Main.SeriesMode", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("Database.Main.SignatureKind", b =>
                {
                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("Database.Main.Token", b =>
                {
                    b.Navigation("AddressBalances");

                    b.Navigation("Contract");

                    b.Navigation("Externals");

                    b.Navigation("Infusions");

                    b.Navigation("TokenDailyPrices");

                    b.Navigation("TokenLogos");
                });

            modelBuilder.Entity("Database.Main.TokenLogoType", b =>
                {
                    b.Navigation("TokenLogos");
                });

            modelBuilder.Entity("Database.Main.Transaction", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Signatures");

                    b.Navigation("TransactionAddresses");
                });

            modelBuilder.Entity("Database.Main.TransactionState", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
