services:
  api:
    image: "explorer-backend-api-${DEPLOY_ENV:-production}"
    container_name: explorer-backend-api-${DEPLOY_ENV:-production}
    build:
      context: ../..
      dockerfile: Backend.Service.Api/Docker/build/Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Release}
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    entrypoint: "./start-api-service-docker.sh"
    ports:
      - "${API_PORT:-9000}:8000"
    networks:
      - api
      - postgresql
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "20m"

networks:
  api:
    name: api-${DEPLOY_ENV:-production}-network
  postgresql:
    name: postgresql-network
    external: true
